### ISSUE TITLE
BrowserEmulator - Unexpected exception

### ISSUE THREAD

**Issue by galaxyeye** [platonai/pulsarr#12]
2022-05-22 16:49:04.067  WARN [r-worker-5] a.p.p.p.b.e.BrowserEmulator - Unexpected exception

java.lang.StringIndexOutOfBoundsException: String index out of range: 15
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:711)
	at ai.platon.pulsar.common.HtmlUtils.isBlankBody(Htmls.kt:107)
	at ai.platon.pulsar.protocol.browser.emulator.EmulateEventHandler.checkHtmlIntegrity(EmulateEventHandler.kt:137)
	at ai.platon.pulsar.protocol.browser.emulator.EmulateEventHandler.onAfterNavigate(EmulateEventHandler.kt:89)
	at ai.platon.pulsar.protocol.browser.emulator.BrowserEmulator.browseWithMinorExceptionsHandled(BrowserEmulator.kt:180)
	at ai.platon.pulsar.protocol.browser.emulator.BrowserEmulator.access$browseWithMinorExceptionsHandled(BrowserEmulator.kt:34)
	at ai.platon.pulsar.protocol.browser.emulator.BrowserEmulator$browseWithMinorExceptionsHandled$1.invokeSuspend(BrowserEmulator.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by platonai** [comment]
Fixed.
