### ISSUE TITLE
Failed to get the total disk space

### ISSUE THREAD

**Issue by platonai** [platonai/pulsarr#19]
`Exception in thread "DefaultDispatcher-worker-1 @sc#1" java.nio.file.FileSystemException: /run/user/1000/doc: Operation not permitted
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileStore.readAttributes(UnixFileStore.java:115)
	at java.base/sun.nio.fs.UnixFileStore.getTotalSpace(UnixFileStore.java:122)
	at ai.platon.pulsar.common.metrics.AppMetrics$Companion.getFreeSpace(AppMetrics.kt:107)
`

`vincent@vincent-KLVC-WXX9:~/workspace/pulsar-1.10.x$ java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

vincent@vincent-KLVC-WXX9:~$ uname -a
Linux vincent-KLVC-WXX9 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
`

Should properly handle the files without correct permition:

`
FileSystems.getDefault().fileStores
    .filter { ByteUnitConverter.convert(totalSpaceOr0(it), "G") > 20 }
    .map { unallocatedSpaceOr0(it) }
    .filter { it > 0 }
`

**Comment by platonai** [comment]
Fixed.
