### ISSUE TITLE
Failed to copy chrome data dir when there is a SingletonSocket symbol link

### ISSUE THREAD

**Issue by platonai** [platonai/pulsarr#29]
21:19:13.336 [main] INFO  a.p.p.b.driver.chrome.ChromeLauncher - User data dir does not exist, copy from prototype | /tmp/pulsar-vincent/context/cx.1iAggh21/pulsar_chrome <- /home/vincent/.pulsar/browser/chrome/prototype/google-chrome
21:19:18.060 [main] WARN  a.p.p.b.driver.chrome.ChromeLauncher - Failed to prepare user data dir
java.lang.IllegalArgumentException: Parameter 'srcFile' is not a file: /home/vincent/.pulsar/browser/chrome/prototype/google-chrome/SingletonSocket
	at org.apache.commons.io.FileUtils.requireFile(FileUtils.java:2737)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:841)
	at org.apache.commons.io.FileUtils.doCopyDirectory(FileUtils.java:1312)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:699)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:630)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:531)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:502)
	at ai.platon.pulsar.browser.driver.chrome.ChromeLauncher.prepareUserDataDir(ChromeLauncher.kt:236)
	at ai.platon.pulsar.browser.driver.chrome.ChromeLauncher.launch(ChromeLauncher.kt:50)
	at ai.platon.pulsar.browser.driver.chrome.ChromeLauncher.launch(ChromeLauncher.kt:61)
	at ai.platon.pulsar.protocol.browser.driver.BrowserFactory.launchChromeDevtoolsBrowser(BrowserFactory.kt:40)
	at ai.platon.pulsar.protocol.browser.driver.BrowserFactory.launch(BrowserFactory.kt:22)
	at ai.platon.pulsar.protocol.browser.driver.BrowserManager.launchIfAbsent$lambda-12(BrowserManager.kt:106)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at ai.platon.pulsar.protocol.browser.driver.BrowserManager.launchIfAbsent(BrowserManager.kt:105)
	at ai.platon.pulsar.protocol.browser.driver.BrowserManager.launch(BrowserManager.kt:38)

**Comment by platonai** [comment]
Fixed.
